### ISSUE TITLE
Replace command by file module (chown)

### ISSUE THREAD

**Issue by nioc** [ovv/ansible-role-wallabag#8]
If I may, here is a little change request: replace `command` module:
```
- name: permissions  # noqa 302
  command: >
    chown -R wallabag:wallabag
    /opt/wallabag/web
    /opt/wallabag/var
    /opt/wallabag/bin
    /opt/wallabag/app/config
    /opt/wallabag/vendor
    /opt/wallabag/data
  when: wallabag_download is changed
```
By `file` module (using variable `wallabag_dir` for changing installation path `/opt/wallabag` and `wallabag_user` for using web server user like `www-data`):
```
- name: Set permissions
  become: yes
  file:
    path: '{{wallabag_dir}}/{{item}}'
    state: directory
    owner: '{{wallabag_user}}'
    group: '{{wallabag_user}}'
    recurse: yes
  with_items:
  - web
  - var
  - bin
  - app/config
  - vendor
  - data
```

And for idempotency, we have to change owner after download:
```
- name: Set permissions for use console
  become: yes
  file:
    path: '{{wallabag_dir}}/'
    state: directory
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    recurse: yes
```
